### ISSUE TITLE
how to use MCRegion to Anvil

### ISSUE THREAD

**Issue by nooneusethisname** [ImagicalCorp/MConverterUltimate#2]

**Comment by k3ithos** [comment]
If you actually read the README you would know.

**Comment by nooneusethisname** [comment]
i read the readme, i've converted some anvils and leveldbs map to mcregion, but i can't use the mcregion -> anvil converter
![image](https://cloud.githubusercontent.com/assets/16216792/12372570/ea88ffb8-bc8f-11e5-8588-a4620ac1fcfd.png)

**Comment by xHFx** [comment]
World called pvpmap is not convertible to the Anvil format

**Comment by legoboy0215** [comment]
Eh... Please don't bump this issue.
