### ISSUE TITLE
"Failed to check folder "world" 's validation. Problem: world is not a valid Anvil folder"

### ISSUE THREAD

**Issue by ajthemacboy** [ImagicalCorp/MConverterUltimate#3]
Whenever I run the Anvil to LevelDB script, I get this error:

```
aj@aj-ugnome:~/dev/MConverterUltimate-master/Anvil to LevelDB$ ./start.sh
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on
Failed to check folder "world" 's validation. Problem: world is not a valid Anvil folder


Map converter for Minecraft:Pocket Edition, from format "LevelDB" to "Anvil", or from format "Anvil" to "LevelDB". (c) ljyloo 2015

Usage:
    java -jar Converter.jar <import folder> <export folder> <type>
Where:
    <import folder> The full path to the folder containing Minecraft:Pocket Edition world
    <export folder> The full path to the folder which you want to export
    <type>  0 represents "LevelDB" to "Anvil", 1 represents "Anvil" to "LevelDB"
Example:
    java -jar Converter.jar /home/ljyloo/LevelDB /home/ljyloo/Anvil 0

```

My 'world' is an exported world from WorldPainter that opens fine in Minecraft 1.8. What am I doing wrong?

**Comment by k3ithos** [comment]
Make sure your world folder is correct... Is it named "world"? Also, make sure so that all the region files are stored in the region folder inside the world folder, with the level file inside the world folder. Sounds confusing? LOL

**Comment by ajthemacboy** [comment]
That's exactly how it is, just a plain world, level.dat, region folder, and session.lock. It also fails with session.lock removed.

**Comment by ajthemacboy** [comment]
If it makes a difference I'm using Java 8.

**Comment by k3ithos** [comment]
Are you sure there are mca files in the region folder?

**Comment by ajthemacboy** [comment]
http://i.imgur.com/dr8SG0Y.png and http://i.imgur.com/1wcoz77.png

**Comment by ajthemacboy** [comment]
ProjectInfinity discovered a workaround on the other issue; specify the region folder as the input instead of the world folder and it works fine. This is still a bug though as the program should use the region folder automatically if it's required.

**Comment by k3ithos** [comment]
Fixed.
