### ISSUE TITLE
This Software Cannot use！

### ISSUE THREAD

**Issue by silence8620** [ImagicalCorp/MConverterUltimate#4]
When it turned .mca to .mcr complete, enter the server, server still cannot load that map, after long time wait , it shows some of world,but the grass will turn black
:(

**Comment by Taki21** [comment]
Folder Structure:
region (FOLDER) {
- ONLY .mcr files Delete all MCA Files!
  }

level.dat

**Comment by legoboy0215** [comment]
You can fix the black grass with http://www88.zippyshare.com/v/925ogSR2/file.html

**Comment by k3ithos** [comment]
@legoboy0215 link expired...
